-- Core
require("bret.core.options")
require("bret.core.keymaps")
require("bret.core.colorscheme")
require("bret.core.autocommands")
require("bret.core.devicons")
require("bret.core.notify")
-- LSP
require("bret.lsp")
-- Plugins
require("bret.plugin_setup")
require("bret.plugins.treesitter")
require("bret.plugins.todo_comments")
require("bret.plugins.autopairs")
require("bret.plugins.lualine")
require("bret.plugins.comment")
require("bret.plugins.nvimtree")
require("bret.plugins.telescope")
require("bret.plugins.go")
require("bret.plugins.cmp")
require("bret.plugins.whichkey")
require("bret.plugins.indentline")
require("bret.plugins.bufferline")
require("bret.plugins.copilot")
require("bret.plugins.toggleterm")
require("bret.plugins.gitsigns")
require("bret.plugins.dap")
require("bret.plugins.dapui")
-- require("bret.plugins.distant")
